### PR TITLE
Fix crash when receiving non-utf8 data

### PR DESCRIPTION
**Pull request by kchibisov**

### CODE REVIEW

**Comment by elinorbgr** [comment]
I wonder if we should rather do some best-effort processing, reading the contents into a Vec<u8>, then converting it using String::from_utf8 and using String::from_utf8_lossy as a fallback.

**Comment by chrisduerr** [comment]
> I wonder if we should rather do some best-effort processing, reading the contents into a Vec<u8>, then converting it using String::from_utf8 and using String::from_utf8_lossy as a fallback.

Honestly sounds like a terrible idea. To me there is no logical explanation why someone would want to paste an image as text.

**Review by chrisduerr — APPROVED** [review]
Ignoring the content when it's invalid sounds like the best choice to me.

**Comment by kchibisov** [comment]
>I wonder if we should rather do some best-effort processing, reading the contents into a Vec<u8>, then converting it using String::from_utf8 and using String::from_utf8_lossy as a fallback.

Well, we're requesting utf8 string, we got non-utf8 string marked as utf8 string, so It doesn't make any sense to speculate on that and trying to make something different out of it.

**Comment by elinorbgr** [comment]
OK, but silently ignoring the error sounds bad to me.

In that case, maybe the clipboard access should signal the error to downstream crates (by returning a Result), so that they decide if/how they inform the user that the clipboard contained invalid data.

**Comment by kchibisov** [comment]
in theory clipboard should return `Vec<u8>` data and `mime` type, so the client will parse it later to something more useful, since clipboard isn't supposed to work only with utf8 text. We can return result for now though.

**Comment by elinorbgr** [comment]
> in theory clipboard should return `Vec<u8>` data and `mime` type, so the client will parse it later to something more useful, since clipboard isn't supposed to work only with utf8 text.

This would require a more complex API though, given a single clipboard item can be provided as several different mime types, from which the receiver can choose which one is more convenient.

**Comment by kchibisov** [comment]
I've decided to return `Result<String>` for now, since we don't handle other mime types anyway.

**Pull request merged**
