### PR TITLE
Update smithay-clipboard to SCTK 0.9.1

### PR DESCRIPTION
**Pull request by kchibisov**
This commit entirely reworks the internal structure of the entire crate,
as well as some of its APIs. This crate only accepts a C pointer to a
Wayland display object, since the target audience of this crate are
libraries without a wayland-client types. Also since seat information is
not presented in such clients most of the time, the clipboard entirely
relies on its seat tracking.

### CODE REVIEW

**Comment by m-hugo** [comment]
**–** # to compile, in case it's different version of `wayland-client` somewhere
**+** # to compile when there is a different version of `wayland-client` somewhere

**Comment by kchibisov** [comment]
Thanks, the comment was a bit messed up at some point.

**Comment by elinorbgr** [comment]
Okay, I'm reviewing this by looking directly at your new code. Given there is not much point in looking at the diff given you basically rewrote the whole thing.

Questions / remarks:

- I see you added `UTF8_STRING` as a MIME type. I'm not frankly opposed to that, but why is this needed? Which apps are using that? Might be worth adding explanation for that given that's not a MIME type in the strict sense.
- Given you create your `Display` with `from_external_display`, you don't need to `forget()` it, it already knows it does not own the connection and [won't try to close it](https://github.com/Smithay/wayland-rs/blob/ead30bdd5b812b9a54a3c5545220a44e870eb0d3/wayland-client/src/native_lib/display.rs#L116-L125)

Other than that, looks good! :+1:

**Comment by kchibisov** [comment]
>I see you added UTF8_STRING as a MIME type. I'm not frankly opposed to that, but why is this needed? Which apps are using that? Might be worth adding explanation for that given that's not a MIME type in the strict sense.

we had this issue in alacritty https://github.com/alacritty/alacritty/issues/3592 , when geany used only this mime type if you look at a `WAYLAND_DEBUG` log in the issue.

>Given you create your Display with from_external_display, you don't need to forget() it, it already knows it does not own the connection and won't try to close it

Nice. I've updated PR.

**Comment by elinorbgr** [comment]
Alright, thanks!

**Pull request merged**
